server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carrental_db
    username: carrentaluser
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      format-sql: true
      #hibernate:
        #enable_lazy_load_trans: true
    # yukarida lazy yapilmis ama eager olmasi gereken yerlerde eager gibi davranir

    # open-in-view default degeri true olarak gelir.
    # iliski lazy yapilsa dahi  view render edilene kadar veya json datasi olusana kadar transaction acik kaliyor
    ##open-in-view: false

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

greenrent:
  app:
    jwtSecret: greenRent@12
    jwtExpirationMs: 86400000

logging:
  file:
    name: logs/greenrent.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
    '[com.greenrent]': DEBUG

info:
  application:
    name: 'GreenRent Backend Application'
    description: 'This is GreenRent Backend App dev by GreenRent Dev Team'
    version: '@project.version@'







