
spring:
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${DBNAME}
    username: ${DBUSERNAME}
    password: ${DBPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
greenrent:
  app:
    jwtSecret: ${SECRETKEY}
    jwtExpirationMs: ${EXPIRATIONTIME}
logging:
  file:
    name: greenrent_prod.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"

  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
    '[com.greenrent]': INFO
management:
  endpoints:
    web:
      exposure:
        include: ['info','health']

  info:
    env:
      enabled: true